/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in and obtain a JWT */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invalidate the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current authenticated user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the current user's password */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all organizations (superadmin only) */
        get: operations["listOrganizations"];
        put?: never;
        /** Provision a new organization (superadmin only) */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organization_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        /** Get organization settings */
        get: operations["getOrganization"];
        /** Update organization settings (admin; tenant fields superadmin-only) */
        put: operations["updateOrganization"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users in the organization (admin only) */
        get: operations["listUsers"];
        put?: never;
        /** Create a user (admin only) */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        /** Get a user by ID (admin only) */
        get: operations["getUser"];
        /** Update a user (admin only) */
        put: operations["updateUser"];
        post?: never;
        /** Delete a user (admin only) */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List templates in the organization */
        get: operations["listTemplates"];
        put?: never;
        /** Create a template (admin only) */
        post: operations["createTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        /** Get a template by ID */
        get: operations["getTemplate"];
        /** Update a template (admin only) */
        put: operations["updateTemplate"];
        post?: never;
        /** Delete a template (admin only) */
        delete: operations["deleteTemplate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reports (submitter sees own; approver/admin see all in org) */
        get: operations["listReports"];
        put?: never;
        /** Create a draft report */
        post: operations["createReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        /** Get a report by ID (with attachments) */
        get: operations["getReport"];
        /** Update a draft or rejected report (submitter only) */
        put: operations["updateReport"];
        post?: never;
        /** Delete a draft report (submitter only) */
        delete: operations["deleteReport"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a draft report for approval */
        post: operations["submitReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a submitted report (approver / admin only) */
        post: operations["approveReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a submitted report with a mandatory comment (approver / admin only) */
        post: operations["rejectReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate the AI summary (admin only; Phase 3, requires ai_summary_enabled) */
        post: operations["regenerateReportSummary"];
        /** Clear the AI summary (admin only; Phase 3) */
        delete: operations["clearReportSummary"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a file attachment (draft / rejected only; max 5 files, 5 MB each) */
        post: operations["uploadAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
                attachment_id: string;
            };
            cookie?: never;
        };
        /** Download an attachment file (authenticated; SHA-256 verified) */
        get: operations["downloadAttachment"];
        put?: never;
        post?: never;
        /** Delete an attachment (submitter; draft / rejected only) */
        delete: operations["deleteAttachment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export reports as CSV (admin only; UTF-8 with BOM) */
        get: operations["exportReportsCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit events (admin only) */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-events/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export audit events as CSV (admin only; itself audited) */
        get: operations["exportAuditEventsCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemDetails: {
            /**
             * @description Stable problem identifier; slug from `docs/terms.md §7`.
             * @example https://nene-field.dev/problems/report-not-found
             */
            type: string;
            /**
             * @description English summary (UI localizes via the slug — ADR 0015).
             * @example Report Not Found
             */
            title: string;
            /** @example 404 */
            status: number;
            /** @description English diagnostic; never shown verbatim to end users. */
            detail?: string;
            /** @description Request-specific URI / identifier. */
            instance?: string;
            errors?: components["schemas"]["ValidationError"][];
        };
        ValidationError: {
            /** @example work_date */
            field: string;
            /** @example work_date is required. */
            message: string;
            /**
             * @description Stable machine code (UI maps to `error.validation.{code}`).
             * @example required
             */
            code: string;
        };
        HealthResponse: {
            /** @example ok */
            status: string;
            /** @example 0.2.0 */
            version?: string;
        };
        /**
         * @example {
         *       "email": "tanaka@example.com",
         *       "password": "********"
         *     }
         */
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: {
            /** @description JWT bearer token (24h default; carries organization_id + role). */
            token: string;
            user: components["schemas"]["UserResponse"];
        };
        ChangePasswordRequest: {
            /** Format: password */
            current_password: string;
            /** Format: password */
            new_password: string;
        };
        /**
         * @example {
         *       "organization_id": "0a8f...c1",
         *       "name": "山田造園",
         *       "slug": "yamada",
         *       "custom_domain": null,
         *       "is_active": true,
         *       "ai_summary_enabled": false,
         *       "notification_email": "kanri@example.com",
         *       "webhook_url": null,
         *       "created_at": "2026-06-01T09:00:00Z",
         *       "updated_at": "2026-06-10T02:30:00Z"
         *     }
         */
        OrganizationResponse: {
            /** Format: uuid */
            organization_id: string;
            name: string;
            /** @description Unique tenant-resolution key (ADR 0013). */
            slug: string;
            /** @description Unique vanity domain (Tier B; superadmin-managed). */
            custom_domain?: string | null;
            is_active: boolean;
            ai_summary_enabled?: boolean;
            /** Format: email */
            notification_email?: string | null;
            webhook_url?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Superadmin only — provisions a new tenant. */
        OrganizationCreateRequest: {
            name: string;
            slug: string;
            custom_domain?: string | null;
            /** @default true */
            is_active: boolean;
        };
        /**
         * @description Admin updates settings (name, AI, notifications, webhook). `slug`,
         *     `custom_domain`, and `is_active` are superadmin-only fields.
         */
        OrganizationUpdateRequest: {
            name?: string;
            ai_summary_enabled?: boolean;
            ai_api_url?: string | null;
            /**
             * Format: password
             * @description Write-only; never returned in any response.
             */
            ai_api_key?: string | null;
            /** Format: email */
            notification_email?: string | null;
            webhook_url?: string | null;
            /** @description Superadmin only. */
            slug?: string;
            /** @description Superadmin only. */
            custom_domain?: string | null;
            /** @description Superadmin only. */
            is_active?: boolean;
        };
        OrganizationListResponse: {
            items: components["schemas"]["OrganizationResponse"][];
            limit: number;
            offset: number;
            total?: number;
        };
        UserResponse: {
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            organization_id: string;
            name: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "submitter" | "approver" | "admin" | "superadmin";
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        UserCreateRequest: {
            name: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "submitter" | "approver" | "admin";
            /** Format: password */
            password: string;
        };
        UserUpdateRequest: {
            name?: string;
            /** @enum {string} */
            role?: "submitter" | "approver" | "admin";
            is_active?: boolean;
        };
        UserListResponse: {
            items: components["schemas"]["UserResponse"][];
            limit: number;
            offset: number;
            total?: number;
        };
        TemplateFieldDefinition: {
            name: string;
            label: string;
            /** @enum {string} */
            type: "text" | "textarea" | "number" | "checkbox" | "date" | "select";
            required: boolean;
            /** @description Options for the `select` type. */
            options?: string[];
        };
        TemplateResponse: {
            /** Format: uuid */
            template_id: string;
            /** Format: uuid */
            organization_id: string;
            name: string;
            description?: string | null;
            fields: components["schemas"]["TemplateFieldDefinition"][];
            is_default: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TemplateCreateRequest: {
            name: string;
            description?: string | null;
            fields: components["schemas"]["TemplateFieldDefinition"][];
            is_default?: boolean;
        };
        TemplateUpdateRequest: {
            name?: string;
            description?: string | null;
            fields?: components["schemas"]["TemplateFieldDefinition"][];
            is_default?: boolean;
        };
        TemplateListResponse: {
            items: components["schemas"]["TemplateResponse"][];
        };
        /** @enum {string} */
        ReportStatus: "draft" | "submitted" | "approved" | "rejected";
        AttachmentSummary: {
            /** Format: uuid */
            attachment_id: string;
            filename: string;
            /** @enum {string} */
            mime_type: "image/jpeg" | "image/png" | "application/pdf";
            /** @description Bytes. */
            file_size: number;
            sha256: string;
            /** Format: date-time */
            created_at: string;
        };
        ReportResponse: {
            /** Format: uuid */
            report_id: string;
            /** Format: uuid */
            organization_id: string;
            /** Format: uuid */
            user_id: string;
            user_name?: string;
            /** Format: uuid */
            template_id?: string | null;
            title: string;
            body: string;
            /** Format: date */
            work_date: string;
            status: components["schemas"]["ReportStatus"];
            tags?: string[];
            project_code?: string | null;
            invoice_work_order_id?: string | null;
            records_entity_id?: string | null;
            ai_summary?: string | null;
            ai_tags?: string[] | null;
            /** Format: date-time */
            submitted_at?: string | null;
            /** Format: date-time */
            approved_at?: string | null;
            /** Format: date-time */
            rejected_at?: string | null;
            /** Format: uuid */
            approver_id?: string | null;
            approver_comment?: string | null;
            attachments?: components["schemas"]["AttachmentSummary"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Condensed report for list views. */
        ReportSummary: {
            /** Format: uuid */
            report_id: string;
            /** Format: uuid */
            user_id: string;
            user_name: string;
            title: string;
            /** Format: date */
            work_date: string;
            status: components["schemas"]["ReportStatus"];
            tags?: string[];
            project_code?: string | null;
            ai_summary?: string | null;
            /** Format: date-time */
            submitted_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ReportCreateRequest: {
            /** Format: uuid */
            template_id?: string | null;
            title: string;
            body: string;
            /** Format: date */
            work_date: string;
            tags?: string[];
            project_code?: string | null;
            invoice_work_order_id?: string | null;
            records_entity_id?: string | null;
        };
        ReportUpdateRequest: {
            title?: string;
            body?: string;
            /** Format: date */
            work_date?: string;
            tags?: string[];
            project_code?: string | null;
            invoice_work_order_id?: string | null;
            records_entity_id?: string | null;
        };
        ApproveRequest: {
            comment?: string | null;
        };
        RejectRequest: {
            comment: string;
        };
        ReportListResponse: {
            items: components["schemas"]["ReportSummary"][];
            limit: number;
            offset: number;
            total?: number;
        };
        AuditEventResponse: {
            /** Format: uuid */
            event_id: string;
            /** Format: uuid */
            organization_id: string;
            /** @description Report / ReportTemplate / ReportAttachment / User / Organization */
            entity_type: string;
            /** Format: uuid */
            entity_id: string;
            /** @description `{entity}.{verb}` from `docs/terms.md §8`. */
            event_name: string;
            /**
             * Format: uuid
             * @description Null for system actions.
             */
            actor_id?: string | null;
            actor_name?: string | null;
            /** @description Sanitized snapshot before the change (null for create); secrets never included. */
            before?: Record<string, never> | null;
            /** @description Sanitized snapshot after the change (null for delete); secrets never included. */
            after?: Record<string, never> | null;
            request_id?: string | null;
            /** Format: date-time */
            occurred_at: string;
        };
        AuditEventListResponse: {
            items: components["schemas"]["AuditEventResponse"][];
            limit: number;
            offset: number;
            total?: number;
        };
    };
    responses: {
        /** @description Missing or invalid token (`unauthorized`). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://nene-field.dev/problems/unauthorized",
                 *       "title": "Unauthorized",
                 *       "status": 401
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated but not permitted, incl. cross-tenant (`forbidden`). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://nene-field.dev/problems/forbidden",
                 *       "title": "Forbidden",
                 *       "status": 403
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource not found in the caller's organization. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://nene-field.dev/problems/report-not-found",
                 *       "title": "Report Not Found",
                 *       "status": 404
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Request validation failure (`validation-failed`). */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://nene-field.dev/problems/validation-failed",
                 *       "title": "Validation Failed",
                 *       "status": 422,
                 *       "detail": "The request body contains invalid values.",
                 *       "errors": [
                 *         {
                 *           "field": "work_date",
                 *           "message": "work_date is required.",
                 *           "code": "required"
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Invalid lifecycle state transition (`report-not-in-submitted-state` / `report-not-editable`). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://nene-field.dev/problems/report-not-in-submitted-state",
                 *       "title": "Report Not In Submitted State",
                 *       "status": 409
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Attachment exceeds the size limit (5 MB) or per-report file count (5). */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://nene-field.dev/problems/payload-too-large",
                 *       "title": "Payload Too Large",
                 *       "status": 413
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Page size (1–100). */
        LimitParam: number;
        /** @description Number of records to skip. */
        OffsetParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listOrganizations: {
        parameters: {
            query?: {
                /** @description Page size (1–100). */
                limit?: components["parameters"]["LimitParam"];
                /** @description Number of records to skip. */
                offset?: components["parameters"]["OffsetParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description Page size (1–100). */
                limit?: components["parameters"]["LimitParam"];
                /** @description Number of records to skip. */
                offset?: components["parameters"]["OffsetParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listReports: {
        parameters: {
            query?: {
                user_id?: string;
                work_date_from?: string;
                work_date_to?: string;
                status?: components["schemas"]["ReportStatus"][];
                tags?: string[];
                project_code?: string;
                sort?: "work_date_desc" | "work_date_asc" | "submitted_at_desc";
                /** @description Page size (1–100). */
                limit?: components["parameters"]["LimitParam"];
                /** @description Number of records to skip. */
                offset?: components["parameters"]["OffsetParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    submitReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK — report is now `submitted` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    approveReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description OK — report is now `approved` (immutable) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    rejectReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description OK — report returns to `draft` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    regenerateReportSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK — summary regenerated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    clearReportSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK — summary cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    downloadAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                    "image/png": unknown;
                    "application/pdf": unknown;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    exportReportsCsv: {
        parameters: {
            query: {
                work_date_from: string;
                work_date_to: string;
                user_id?: string;
                project_code?: string;
                status?: components["schemas"]["ReportStatus"][];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                entity_type?: string;
                entity_id?: string;
                actor_id?: string;
                event_name?: string;
                occurred_from?: string;
                occurred_to?: string;
                /** @description Page size (1–100). */
                limit?: components["parameters"]["LimitParam"];
                /** @description Number of records to skip. */
                offset?: components["parameters"]["OffsetParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    exportAuditEventsCsv: {
        parameters: {
            query: {
                occurred_from: string;
                occurred_to: string;
                entity_type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
}
