<?php

declare(strict_types=1);

namespace NeneField\Attachment;

/**
 * Binary storage for attachment files, addressed by an opaque `storageKey`. The
 * key is generated by the application (never derived from the original filename)
 * and is never exposed in any API response (legal-compliance NF7).
 */
interface AttachmentStorageInterface
{
    public function write(string $storageKey, string $contents): void;

    /**
     * @throws AttachmentStorageException when the object cannot be read
     */
    public function read(string $storageKey): string;

    public function delete(string $storageKey): void;

    public function exists(string $storageKey): bool;
}
